#!/usr/bin/env python3
"""
Add high-quality LLM-generated English sentences to vocabulary words.
Each sentence is carefully crafted to demonstrate proper word usage for language learners.
"""

import openpyxl

# High-quality sentences generated by LLM for each word
# Each word gets 3 carefully crafted example sentences
LLM_SENTENCES = {
    "step": [
        "She took a careful step forward and knocked on the heavy wooden door.",
        "The first step toward achieving your goals is creating a clear plan.",
        "He missed a step on the dark staircase and nearly fell."
    ],
    "dead": [
        "The flowers in the garden were completely dead after the harsh winter frost.",
        "My phone battery is dead, so I can't call anyone right now.",
        "There was dead silence in the room when the shocking news was announced."
    ],
    "earth": [
        "The earth revolves around the sun once every 365 days.",
        "Farmers prepare the earth carefully before planting their crops in spring.",
        "Scientists believe that protecting the earth is crucial for future generations."
    ],
    "lost": [
        "I lost my wallet somewhere between the restaurant and the parking garage.",
        "The soccer team lost the final match despite playing their best.",
        "Without a map or GPS, we felt completely lost in the unfamiliar neighborhood."
    ],
    "sea": [
        "The vast blue sea stretched endlessly toward the horizon.",
        "Sailors have navigated the sea using stars for thousands of years.",
        "We spent our summer vacation swimming and relaxing by the sea."
    ],
    "note": [
        "She left a brief note on the kitchen table explaining where she had gone.",
        "Please note that the meeting has been rescheduled for next Tuesday.",
        "The detective took careful note of every detail at the crime scene."
    ],
    "account": [
        "I need to check my bank account to see if my salary has been deposited.",
        "The witness gave a detailed account of everything she had seen that night.",
        "You must take into account all the risks before making this important decision."
    ],
    "forth": [
        "The pendulum swung back and forth in a steady, rhythmic motion.",
        "From that day forth, he dedicated his life to helping others.",
        "The speaker brought forth compelling evidence to support her argument."
    ],
    "watch": [
        "My grandfather gave me his antique gold watch before he passed away.",
        "We decided to watch a movie together on Friday evening.",
        "The security guard must watch the monitors carefully throughout the night."
    ],
    "short": [
        "The meeting was mercifully short, lasting only fifteen minutes.",
        "She has beautiful short hair that requires very little maintenance.",
        "We're running short on time, so please finish quickly."
    ],
    "please": [
        "Could you please pass me the salt when you get a chance?",
        "It's impossible to please everyone all the time.",
        "Please remember to turn off the lights before leaving the building."
    ],
    "I'll": [
        "Don't worry about the dishes; I'll wash them after dinner.",
        "I'll call you tomorrow morning to discuss our travel plans.",
        "If it rains, I'll bring an umbrella for both of us."
    ],
    "family": [
        "My entire family gathers together every year for Thanksgiving dinner.",
        "She comes from a large family with six brothers and sisters.",
        "Balancing work and family responsibilities can be quite challenging."
    ],
    "month": [
        "January is typically the coldest month of the year in this region.",
        "She has been studying Spanish for three months now.",
        "The rent is due on the first day of every month."
    ],
    "sort": [
        "What sort of music do you prefer listening to?",
        "Please help me sort these documents alphabetically by last name.",
        "She's the sort of person who always arrives exactly on time."
    ],
    "fine": [
        "The weather today is absolutely fine for a picnic in the park.",
        "If you park illegally, you might have to pay a hefty fine.",
        "After recovering from the illness, she felt perfectly fine again."
    ],
    "offer": [
        "The company made her an attractive job offer with excellent benefits.",
        "I'd like to offer my sincere apologies for the misunderstanding.",
        "The store is offering a special discount on all electronic items this week."
    ],
    "hard": [
        "The exam was extremely hard, and many students struggled to finish it.",
        "She worked hard all year to achieve her goal of getting promoted.",
        "The ground was frozen hard after three consecutive nights of frost."
    ],
    "England": [
        "England is famous for its historic castles and beautiful countryside.",
        "Shakespeare, one of the greatest playwrights, was born in England.",
        "The weather in England is often rainy and unpredictable."
    ],
    "really": [
        "I really appreciate all the help you've given me with this project.",
        "The concert was really amazing; the band played for three hours straight.",
        "Do you really think we can finish this work before the deadline?"
    ],
    "different": [
        "These two paintings look similar, but they're actually quite different.",
        "Learning a foreign language exposes you to different cultures and perspectives.",
        "We need to try a different approach since this method isn't working."
    ],
    "happen": [
        "Accidents can happen when people don't follow safety regulations carefully.",
        "What will happen if we don't submit the application by Friday?",
        "I happened to meet my old friend at the airport yesterday."
    ],
    "regard": [
        "He has always held his grandmother in the highest regard.",
        "With regard to your question, I'll need to consult my supervisor first.",
        "The team showed little regard for the safety warnings."
    ],
    "possible": [
        "Is it possible to reschedule our meeting for later in the week?",
        "The doctors did everything possible to save the patient's life.",
        "We should explore every possible solution before giving up."
    ],
    "mile": [
        "The nearest gas station is about five miles down this road.",
        "She jogs at least three miles every morning before breakfast.",
        "You could see the smoke from the fire for miles around."
    ],
    "fell": [
        "The child fell off the swing and scraped her knee badly.",
        "Stock prices fell sharply after the unexpected announcement.",
        "A heavy silence fell over the crowd when the ceremony began."
    ],
    "towards": [
        "The cat walked slowly towards the bowl of food.",
        "She has always had a positive attitude towards learning new skills.",
        "The government is taking important steps towards reducing carbon emissions."
    ],
    "human": [
        "Every human being deserves to be treated with dignity and respect.",
        "Making mistakes is human; we all err from time to time.",
        "The human brain is incredibly complex and not yet fully understood."
    ],
    "bear": [
        "The massive grizzly bear caught a salmon in the rushing river.",
        "She couldn't bear to watch the sad ending of the movie.",
        "You'll have to bear the consequences of your irresponsible actions."
    ],
    "deep": [
        "The lake is dangerously deep in the center, so be very careful.",
        "He fell into a deep sleep and didn't wake until morning.",
        "She felt a deep sense of gratitude for all their help and support."
    ],
    "kept": [
        "She kept her grandmother's jewelry in a special locked box.",
        "The secret was kept hidden for more than twenty years.",
        "They kept walking despite the heavy rain and cold wind."
    ],
    "effect": [
        "The new law will have a significant effect on small businesses.",
        "Climate change is having a devastating effect on polar ice caps.",
        "The medicine should take effect within thirty minutes."
    ],
    "include": [
        "The tour package will include accommodation, meals, and transportation.",
        "Please include your contact information on the application form.",
        "The list of invited guests includes several distinguished professors."
    ],
    "able": [
        "After months of practice, she was finally able to play the difficult piano piece.",
        "Will you be able to attend the conference next month?",
        "The new system enables users to access their files from anywhere."
    ],
    "save": [
        "The firefighters managed to save everyone from the burning building.",
        "I'm trying to save money for a trip to Europe next summer.",
        "Please remember to save your work frequently to avoid losing it."
    ],
    "met": [
        "I met my best friend on the first day of college.",
        "The committee met yesterday to discuss the proposed changes.",
        "She felt nervous before she met her boyfriend's parents for the first time."
    ],
    "stop": [
        "The bus will stop at the corner near the library.",
        "Please stop making so much noise; people are trying to work.",
        "There's a rest stop about ten miles ahead where we can get coffee."
    ],
    "purpose": [
        "The main purpose of this meeting is to discuss the budget for next year.",
        "He felt that his life lacked meaning and purpose.",
        "She did it on purpose, not by accident as she claimed."
    ],
    "five": [
        "There are five people waiting in line ahead of us.",
        "The store opens at five o'clock in the morning.",
        "She has been studying piano for five years now."
    ],
    "minute": [
        "Wait just a minute while I grab my coat from the closet.",
        "The journey takes approximately forty-five minutes by train.",
        "He examined every minute detail of the contract before signing it."
    ],
    "change": [
        "Climate change is one of the most pressing issues of our time.",
        "Do you have change for a twenty-dollar bill?",
        "She decided to change her major from biology to psychology."
    ],
    "provide": [
        "The company will provide all necessary equipment and training.",
        "Parents must provide love, guidance, and support to their children.",
        "This textbook provides clear explanations of complex mathematical concepts."
    ],
    "produce": [
        "This factory can produce up to ten thousand units per day.",
        "The local farmers produce excellent organic vegetables.",
        "The investigation failed to produce any concrete evidence."
    ],
    "art": [
        "The museum has an impressive collection of modern art.",
        "She decided to study art history at university.",
        "Cooking is both a science and an art that requires practice."
    ],
    "consider": [
        "We should carefully consider all options before making a final decision.",
        "Many people consider him to be the greatest athlete of all time.",
        "I'm considering applying for a job abroad next year."
    ],
    "french": [
        "She speaks French fluently after living in Paris for five years.",
        "We enjoyed delicious French cuisine at the new restaurant downtown.",
        "The French Revolution began in 1789 and changed European history."
    ],
    "sit": [
        "Please sit down and make yourself comfortable.",
        "The cat likes to sit in the sunny spot by the window.",
        "We sat through a three-hour meeting without a single break."
    ],
    "start": [
        "The concert will start at eight o'clock sharp.",
        "She decided to start her own business after years of working for others.",
        "Getting started is often the hardest part of any project."
    ],
    "clear": [
        "The instructions are clear and easy to follow.",
        "After the storm passed, the sky became perfectly clear again.",
        "Please clear the table before we serve dessert."
    ],
    "dark": [
        "It gets dark very early during the winter months.",
        "She has beautiful dark eyes and long dark hair.",
        "The room was so dark that we couldn't see anything at all."
    ],
}


def main():
    print("="*70)
    print("Adding High-Quality LLM-Generated Sentences")
    print("="*70)

    print("\nLoading MyEnglishWords.xlsx...")
    wb = openpyxl.load_workbook('MyEnglishWords.xlsx')
    ws = wb.active
    print("✓ File loaded successfully")

    print("\nAdding LLM-generated sentences...")
    updated_count = 0

    for row in range(2, ws.max_row + 1):
        word = ws.cell(row=row, column=1).value
        if word and word.lower() in LLM_SENTENCES:
            sentences = LLM_SENTENCES[word.lower()]
            ws.cell(row=row, column=9).value = sentences[0]
            ws.cell(row=row, column=10).value = sentences[1]
            ws.cell(row=row, column=11).value = sentences[2]
            updated_count += 1

    print(f"✓ Updated {updated_count} words with LLM-generated sentences")

    print("\nSaving file...")
    wb.save('MyEnglishWords.xlsx')
    print("✓ File saved successfully!")

    print("\n" + "="*70)
    print("COMPLETE!")
    print("="*70)


if __name__ == "__main__":
    main()
