#!/usr/bin/env python3
"""
LLM-Generated Sentences for Batch 4 (Rows 102-201) - 100 words
High-quality, contextually appropriate sentences for English language learners
"""

sentences = {
    102: ["She doesn't have much time left to finish the project.", "Thank you so much for all your help during this difficult period.", "There isn't much difference between the two products in terms of quality."],
    103: ["I want to start my own business within the next five years.", "She designed and built her own website from scratch.", "Each student must complete their own assignment independently."],
    104: ["The movie was too long and could have been shortened significantly.", "She has long blonde hair that reaches down to her waist.", "How long have you been studying English at this school?"],
    105: ["Please sit down and make yourself comfortable in the living room.", "The ball rolled down the hill and into the pond.", "I need to write down your phone number before I forget it."],
    106: ["After the storm passed, a beautiful rainbow appeared in the sky.", "She always exercises after work to relieve stress and stay healthy.", "We'll discuss the details after everyone arrives at the meeting."],
    107: ["This is the first time I've ever tried authentic Japanese sushi.", "First impressions are important when meeting someone new for business.", "She won first place in the national piano competition last year."],
    108: ["Mr. Thompson has been teaching mathematics at our school for decades.", "The package is addressed to Mr. and Mrs. Anderson.", "Excuse me, Mr. President, may I ask you a question?"],
    109: ["She's a good listener who always offers helpful advice to friends.", "This restaurant serves really good food at reasonable prices.", "Having good communication skills is essential in any career."],
    110: ["Even experienced hikers found the mountain trail challenging and steep.", "She didn't even notice when I walked into the room quietly.", "The children remained calm even when the fire alarm sounded."],
    111: ["Could you please show me the way to the nearest subway station?", "There's more than one way to solve this mathematical equation correctly.", "That's just the way things are sometimes in unpredictable life."],
    112: ["My grandfather is ninety years old but still very active and sharp.", "The old farmhouse has been abandoned for many years now.", "They're demolishing the old factory to build new apartment buildings."],
    113: ["Three men were arrested in connection with the robbery yesterday evening.", "The men's basketball team won the championship trophy this season.", "All men and women are created equal under the law."],
    114: ["Can you take the dog for a walk while I prepare dinner?", "It takes approximately two hours to drive from here to the coast.", "Please take your shoes off before entering the house, thank you."],
    115: ["I've never been to Australia, but I'd love to visit someday soon.", "She never forgets a birthday or anniversary of family and friends.", "Never give up on your dreams, no matter how difficult they seem."],
    116: ["Most people prefer coffee to tea in the morning for energy.", "The most important decision of her life was choosing her career path.", "This is the most beautiful garden I've ever seen in my travels."],
    117: ["Where did you go on vacation last summer with your family?", "I don't know where I put my car keys this morning.", "The hotel where we stayed had an amazing view of the ocean."],
    118: ["Shall we meet at six o'clock for dinner at the Italian restaurant?", "I shall never forget your kindness during my time of need.", "What shall we do about this problematic situation facing our team?"],
    119: ["Paris is a wonderful place to visit during the springtime season.", "Please put the books back in their proper place on the shelf.", "She won first place in the swimming competition at the Olympics."],
    120: ["I think it's going to rain later this afternoon based on the clouds.", "What do you think about the new policy changes at work?", "Let me think about your proposal and get back to you tomorrow."],
    121: ["Those shoes are much more comfortable than the ones I'm wearing now.", "Who are those people standing by the entrance of the building?", "In those days, people didn't have access to modern technology like smartphones."],
    122: ["She came home late last night after working overtime at the office.", "The opportunity came at exactly the right time in her career.", "He came from a small village but achieved great success in the city."],
    123: ["He taught himself how to play guitar by watching online tutorials.", "The king himself attended the ceremony to honor the brave soldiers.", "My son made himself breakfast this morning before school for the first time."],
    124: ["Last year was one of the best years of my entire life.", "She graduates from medical school next year in the spring semester.", "The company celebrates its fiftieth year of operation this month."],
    125: ["Life is full of unexpected surprises and wonderful opportunities for growth.", "She dedicated her life to helping disadvantaged children in developing countries.", "The quality of life in this city has improved dramatically over time."],
    126: ["I can't imagine life without music, art, and creative expression around me.", "He left the house without his wallet and had to return home.", "The team won the game without their star player who was injured."],
    127: ["You seem tired today; did you sleep well last night?", "The solution may seem simple, but it's actually quite complex when examined.", "Things always seem worse at night than they do in the morning light."],
    128: ["She has beautiful green eyes that sparkle when she smiles happily.", "Keep your eye on the ball and concentrate on your technique carefully.", "The detective has a sharp eye for details that others often miss completely."],
    129: ["She speaks English very well after studying it for only two years.", "The project didn't go as well as we had originally hoped it would.", "Well, I suppose we should get started on the presentation right away now."],
    130: ["We walked through the park on our way to the downtown shopping district.", "She read through the entire contract before signing it at the lawyer's office.", "The train goes through several tunnels as it crosses the mountain range daily."],
    131: ["The thought of traveling alone to a foreign country made her both nervous and excited.", "He was lost in thought when I called his name three times loudly.", "She thought carefully before making such an important life decision about her future."],
    132: ["You might want to bring an umbrella because rain is forecast for today.", "She might be late to the meeting due to heavy traffic on the highway.", "This treatment might help reduce your symptoms significantly within a few weeks."],
    133: ["How did you learn to cook such delicious meals so quickly and easily?", "Tell me how I can help you with this challenging project at work.", "I don't understand how the machine works despite reading the instruction manual."],
    134: ["I'll be back in fifteen minutes after I pick up the groceries from the store.", "She looked back at her childhood with fond memories of summer vacations and family.", "The pain in my back has been bothering me for several days now."],
    135: ["Please call me when you arrive safely at your destination tonight without fail.", "I heard someone call my name loudly from across the crowded shopping mall.", "We received an emergency call at midnight about a problem at the factory."],
    136: ["I am so grateful for all the support you've given me throughout this journey.", "I am confident that we can solve this problem together as a team effectively.", "I am planning to visit my grandparents next month during the school holidays."],
    137: ["The coffee is too hot to drink right now; let it cool down first.", "She's too busy to meet with us today, but she's free tomorrow afternoon.", "I ate too much at dinner and now I feel uncomfortably full and sluggish."],
    138: ["Please use the side entrance when you arrive at the building tomorrow morning.", "I use this app every day to track my fitness goals and progress carefully.", "What kind of shampoo do you use to keep your hair so shiny and healthy?"],
    139: ["I don't want to make the same mistake again in the future ever.", "Could you please say that again because I didn't hear you clearly the first time?", "Let's meet again next week to discuss the progress of our ongoing project."],
    140: ["I'll give you my phone number so we can stay in touch after graduation.", "Please give my regards to your family when you see them this weekend.", "The teacher will give us our test results on Monday morning in class."],
    141: ["Many students struggle with mathematics during their first year of high school studies.", "How many times have I told you not to leave your dirty dishes in the sink?", "There are too many choices on the menu; I can't decide what to order."],
    142: ["Come here and let me show you something interesting I discovered online today.", "We've lived here for ten years and love this friendly neighborhood very much.", "Here is the document you requested for tomorrow's important meeting with clients."],
    143: ["I didn't understand a single word of what he said in his presentation today.", "She kept her word and returned the borrowed money exactly when she promised.", "The word 'love' has many different meanings across various cultures and languages worldwide."],
    144: ["Millions of people around the world use social media every single day now.", "Some people enjoy cold weather while others prefer warm tropical climates year-round.", "The people in this community are very friendly and welcoming to newcomers always."],
    145: ["This is the last piece of cake; would you like to have it for dessert?", "We spent our last day of vacation relaxing on the beautiful sandy beach together.", "When was the last time you visited your hometown and saw your old friends?"],
    146: ["I need to get some sleep before my early morning flight to London tomorrow.", "Where can I get good Italian food in this neighborhood at reasonable prices?", "Please get in touch with me as soon as you receive this urgent message today."],
    147: ["She calls her mother every Sunday evening without fail to catch up on news.", "Every student in the class passed the final exam with flying colors this semester.", "I try to learn something new every day to keep my mind sharp and engaged."],
    148: ["They went to Paris for their honeymoon and had a wonderful romantic time there.", "The meeting went better than expected, and everyone agreed on the new proposal unanimously.", "Where did you go after you left the party so early last Saturday night?"],
    149: ["We're staying at the same hotel we stayed at last year during our summer vacation.", "She ordered the same dish at the restaurant every time she visits without exception.", "Both twins have the same eye color, hair color, and even the same laugh."],
    150: ["This part of the city is known for its excellent restaurants and vibrant nightlife scene.", "I need to replace a part in my car's engine that's been making strange noises.", "The best part of the concert was when they played their most famous hit song."],
    151: ["I love spending time with my family on weekends doing activities together outdoors.", "She fell in love with him the first time they met at the coffee shop.", "My children love reading adventure stories before bedtime every single night without fail."],
    152: ["I found twenty dollars in my old jacket pocket that I had completely forgotten about.", "She finally found her lost keys under the couch cushion in the living room yesterday.", "Researchers have found a possible cure for this disease after years of dedicated study."],
    153: ["Don't be afraid to ask questions if you don't understand something in class today.", "Can I ask you a personal favor regarding my situation at work right now?", "She's going to ask her boss for a raise during their meeting tomorrow afternoon."],
    154: ["The birds flew away when they heard the loud noise from the construction site nearby.", "Put those cleaning supplies away in the closet when you're finished using them please.", "The vacation house is only an hour away from the city by car or train."],
    155: ["The cat is hiding under the bed because it's scared of the thunderstorm outside.", "Children under the age of twelve must be accompanied by an adult guardian always.", "She discovered a hidden treasure chest under the floorboards of the old house yesterday."],
    156: ["Many people pray to God for guidance, strength, and comfort during difficult times always.", "Oh my God, I can't believe we won the lottery jackpot this weekend!", "The ancient Greeks believed in many gods who controlled different aspects of nature and life."],
    157: ["Please turn off the lights when you leave the room to save electricity and money.", "Turn left at the traffic light and then continue straight for two more blocks.", "It's your turn to present your project to the class this morning after break."],
    158: ["My younger sister is still quite young, only sixteen years old this year.", "The young couple just bought their first house together in the suburban neighborhood nearby.", "He's too young to understand the complexity of adult relationships and responsibilities fully."],
    159: ["She has a beautiful face with delicate features and a warm, genuine smile always.", "He couldn't face his friends after making such an embarrassing mistake at the party.", "The company must face the consequences of their poor environmental decisions and practices now."],
    160: ["Despite all the noise, the baby is still sleeping peacefully in the nursery upstairs.", "I still remember my first day of school like it was yesterday morning vividly.", "Are you still working at the same company you joined five years ago?"],
    161: ["She shook her head to indicate that she disagreed with the proposal completely.", "I have a terrible headache and need to take some medicine right away now.", "The company's head office is located in downtown Manhattan on Fifth Avenue."],
    162: ["While you were out shopping, your sister called to say she'll visit tomorrow afternoon.", "I learned a lot while working at that company for five years in my twenties.", "Some people like tea while others prefer coffee for their morning caffeine boost daily."],
    163: ["I just received your email and will respond to it shortly this afternoon promptly.", "She's not just beautiful; she's also incredibly intelligent and kind to everyone always.", "Just do your best and don't worry about what other people think of you ever."],
    164: ["She speaks French, and she also speaks Spanish and Italian fluently without any accent.", "The restaurant serves delicious food and also offers live music on Friday evenings regularly.", "I'm tired, and I'm also hungry because I skipped lunch today to finish work."],
    165: ["They bought a beautiful old house with a large garden in the countryside last spring.", "The White House is the official residence of the President of the United States always.", "Can you come over to my house after work to help me move some furniture?"],
    166: ["The king ruled the kingdom wisely and fairly for over forty prosperous years successfully.", "King Henry VIII of England had six wives during his controversial and dramatic reign.", "In chess, the king is the most important piece that must be protected at all costs."],
    167: ["Turn right at the next intersection and you'll see the hospital on your left side.", "You have the right to remain silent when questioned by police officers during arrest.", "I think you made the right decision by accepting that excellent job offer yesterday."],
    168: ["What's your name, and where are you from originally before moving here recently?", "She changed her name legally after getting married to her husband last summer officially.", "The company has built a strong name for itself in the technology industry worldwide successfully."],
    169: ["Can you tell me how to get to the train station from here please?", "I didn't want to tell her the bad news over the phone call yesterday evening.", "The test results will tell us whether the treatment is working effectively or not soon."],
    170: ["Where do you live now after moving out of your parents' house last year?", "My grandparents have lived in the same small town their entire lives happily together.", "I want to live in a place with warm weather and beautiful beaches someday soon."],
    171: ["I haven't finished my homework yet, but I'll complete it before tomorrow's class deadline.", "The store hasn't opened yet; it opens at nine o'clock every morning regularly.", "She's young yet already incredibly accomplished in her professional career path so far."],
    172: ["I want to travel around the world and experience different cultures and cuisines everywhere.", "Do you want to join us for dinner tonight at the new restaurant downtown?", "All she wants is to be happy and spend time with people she loves dearly."],
    173: ["Please follow the instructions carefully to avoid making any costly mistakes during assembly.", "I follow several interesting blogs about cooking, travel, and photography online daily regularly.", "The dog will follow you anywhere because he loves you so much unconditionally always."],
    174: ["I'm tired; though I'll still go to the gym to exercise this evening as planned.", "Though it was raining heavily, we decided to go hiking anyway with proper gear.", "She's very young, though she's already achieved more than most people twice her age."],
    175: ["What do you mean by that confusing statement you just made a minute ago?", "I didn't mean to hurt your feelings with my thoughtless comment earlier today at lunch.", "The red light means you must stop your vehicle completely at the intersection now."],
    176: ["Everyone was against the proposal except for one person who supported it strongly yesterday.", "The team played well but unfortunately lost against their rivals in overtime last night sadly.", "She leaned against the wall while waiting for the bus to arrive at the stop."],
    177: ["This is the best movie I've ever seen in my entire life without any doubt.", "Have you ever been to New York City during the winter holiday season before now?", "She's the kindest person I've ever met in all my years of life and work."],
    178: ["Please put the dishes away in the cupboard after you wash and dry them thoroughly.", "I need to put on my coat because it's cold outside this morning right now.", "She put a lot of effort into preparing for the important presentation yesterday carefully."],
    179: ["My best friend is someone I can always count on during difficult times without hesitation.", "She invited all her friends to celebrate her birthday party at her house this weekend.", "A good friend will tell you the truth even when it's hard to hear sometimes honestly."],
    180: ["Please turn off your cell phone before the movie starts in the theater momentarily.", "The meeting has been called off due to the director's unexpected illness this morning sadly.", "Get off the bus at the third stop and walk two blocks to reach the museum."],
    181: ["There's nothing in the refrigerator; we need to go grocery shopping immediately today.", "Nothing can stop her from achieving her dreams and goals in life no matter what.", "He said nothing during the entire meeting, which seemed quite unusual for him actually."],
    182: ["She has a kind heart and always helps people in need whenever possible generously.", "Regular exercise is good for your heart and overall health and wellness long-term definitely.", "I learned that poem by heart when I was just a young child in school."],
    183: ["Time seems to pass quickly when you're enjoying yourself with good friends and family.", "Please pass the salt and pepper when you get a chance during dinner tonight please.", "Did you pass your driving test on the first attempt or did you need to retake it?"],
    184: ["I once met a famous actor at a restaurant in Los Angeles during a vacation trip.", "Once you learn to ride a bicycle, you never forget how to do it ever.", "She visits her grandmother once a week every Sunday afternoon without fail regularly."],
    185: ["Would you like another cup of coffee or tea with your breakfast this morning perhaps?", "One door closes and another opens, bringing new opportunities for growth and success always.", "Let's try another approach to solving this complex problem together as a team effectively."],
    186: ["She turned left at the corner and walked toward the library building down the street.", "He left his job to pursue his dream of becoming a professional artist full-time finally.", "There are only two cookies left in the jar on the kitchen counter right now."],
    187: ["People from all over the world visit this famous monument every year in huge numbers.", "The internet has connected the entire world in ways we never imagined possible before now.", "She traveled around the world for a year before starting her new job at the company."],
    188: ["I don't mind helping you move to your new apartment this weekend at all honestly.", "Keep an open mind when you meet new people and experience different cultures abroad always.", "She changed her mind about studying law and decided to study medicine instead finally."],
    189: ["I can't find my glasses anywhere in the house despite looking everywhere carefully already.", "Did you find the information you were looking for in the library database online?", "We need to find a solution to this problem as soon as possible before it gets worse."],
    190: ["I saw your brother at the shopping mall yesterday afternoon with his friends together.", "She saw an incredible shooting star last night while stargazing in the backyard alone.", "Have you seen the latest movie everyone's talking about this week at the theater?"],
    191: ["She plans to return to university next year to complete her advanced degree program finally.", "Please return the library books before they're overdue and you have to pay fines.", "The migrating birds return to this area every spring to nest and raise their young safely."],
    192: ["We stayed up all night studying for the important exam the next morning at school.", "The stars are clearly visible on a clear night away from city lights and pollution.", "They enjoyed a romantic dinner by candlelight last night at the fancy Italian restaurant downtown."],
    193: ["Please fill out this form completely and return it to the office by Friday afternoon.", "Exercise is an important form of self-care that benefits both body and mind significantly.", "Water can exist in three different forms: solid ice, liquid water, and gaseous steam."],
    194: ["The company launched a new product line that's been very successful in the market already.", "She just moved into her beautiful new apartment in the city center last week excitedly.", "I need to buy new shoes because my old ones are worn out and uncomfortable now."],
    195: ["I have three children: two daughters and one son in elementary school currently now.", "The meeting will start in three hours, so we have plenty of time to prepare thoroughly.", "She speaks three languages fluently: English, Spanish, and French without any accent whatsoever."],
    196: ["She took her children to the park to play on the swings and slides yesterday afternoon.", "It took me five years to complete my university degree while working part-time successfully.", "He took a deep breath before diving into the cold swimming pool water bravely."],
    197: ["My father works as an engineer at a large construction company in the city downtown.", "Her father taught her how to ride a bicycle when she was just five years old.", "Father's Day is celebrated on the third Sunday of June in many countries worldwide annually."],
    198: ["She always arrives early to appointments and meetings to be punctual and professional consistently.", "My grandmother always says that honesty is the best policy in all situations without exception.", "I always forget where I put my car keys in the morning when rushing to leave."],
    199: ["Mrs. Johnson is my favorite teacher because she explains things clearly and patiently always.", "The package is addressed to Mr. and Mrs. Smith at their home address correctly.", "May I speak with Mrs. Rodriguez regarding the appointment scheduled for tomorrow afternoon please?"],
    200: ["Please set the table for dinner while I finish cooking the main course in the kitchen.", "The sun will set at approximately seven o'clock this evening according to the forecast.", "They set ambitious goals for themselves and worked hard to achieve them successfully eventually."],
    201: ["Each student must submit their assignment individually by the deadline specified on the syllabus.", "Each room in the hotel has its own private bathroom and balcony with a view.", "We meet each other every Friday evening for dinner and conversation about the week."]
}

if __name__ == "__main__":
    import openpyxl
    print("Updating Excel file with LLM-generated sentences (Batch 4)...")
    wb = openpyxl.load_workbook('MyEnglishWords.xlsx')
    ws = wb.active
    count = 0
    for row_num, sents in sentences.items():
        ws.cell(row=row_num, column=9).value = sents[0]
        ws.cell(row=row_num, column=10).value = sents[1]
        ws.cell(row=row_num, column=11).value = sents[2]
        count += 1
    wb.save('MyEnglishWords.xlsx')
    print(f"✓ Updated {count} words with {count * 3} new sentences!")
    print(f"✓ Total progress: 200/20050 words completed (1.0%)")
